export const vehicleOptions = {
  audi: [
    "a1",
    "a3",
    "a4",
    "a5",
    "a6",
    "q2",
    "q3",
    "q5",
    "q7",
    "tt",
  ],
  bmw: [
    "1 series",
    "2 series",
    "3 series",
    "4 series",
    "5 series",
    "x1",
    "x2",
    "x3",
    "x4",
    "x5",
  ],
  citroen: ["berlingo", "c1", "c3", "c3 aircross", "c4", "c5 aircross", "ds3"],
  dacia: ["duster", "jogger", "sandero", "sandero stepway"],
  fiat: ["500", "500x", "panda", "tipo"],
  ford: [
    "b-max",
    "c-max",
    "ecosport",
    "fiesta",
    "focus",
    "galaxy",
    "ka",
    "kuga",
    "mondeo",
    "puma",
    "s-max",
  ],
  honda: ["accord", "civic", "cr-v", "hr-v", "jazz"],
  hyundai: ["i10", "i20", "i30", "ioniq", "ix35", "kona", "tucson"],
  jaguar: ["e-pace", "f-pace", "xe", "xf", "xj"],
  kia: [
    "ceed",
    "niro",
    "picanto",
    "proceed",
    "rio",
    "sorento",
    "sportage",
    "stonic",
  ],
  "land rover": [
    "defender",
    "discovery",
    "discovery sport",
    "freelander",
    "range rover sport",
  ],
  lexus: ["ct", "is", "nx", "rx", "ux"],
  mazda: ["2", "3", "6", "cx-3", "cx-30", "cx-5", "mx-5"],
  mercedes: [
    "a class",
    "b class",
    "c class",
    "cla",
    "cls",
    "e class",
    "gla",
    "glb",
    "glc",
  ],
  mg: ["3", "gs", "hs", "zs"],
  mini: ["clubman", "cooper", "countryman", "hatch"],
  nissan: ["juke", "leaf", "micra", "note", "qashqai", "x-trail"],
  peugeot: [
    "108",
    "2008",
    "208",
    "3008",
    "308",
    "5008",
    "508",
    "partner",
  ],
  renault: ["captur", "clio", "kadjar", "megane", "scenic"],
  "range rover": ["evoque", "sport", "velar"],
  seat: ["arona", "ateca", "ibiza", "leon"],
  skoda: [
    "citigo",
    "fabia",
    "kamiq",
    "karoq",
    "kodiaq",
    "octavia",
    "superb",
    "yeti",
  ],
  suzuki: ["swift", "sx4 s-cross", "vitara"],
  toyota: [
    "auris",
    "avensis",
    "aygo",
    "c-hr",
    "corolla",
    "prius",
    "rav4",
    "yaris",
  ],
  vauxhall: [
    "adam",
    "astra",
    "corsa",
    "crossland",
    "grandland",
    "insignia",
    "meriva",
    "mokka",
    "vectra",
    "viva",
    "zafira",
  ],
  volkswagen: [
    "arteon",
    "golf",
    "passat",
    "polo",
    "t-cross",
    "t-roc",
    "tiguan",
    "touareg",
    "touran",
    "up",
  ],
  volvo: ["s60", "s90", "v40", "v60", "xc40", "xc60", "xc90"],
} as const;

export type VehicleMake = keyof typeof vehicleOptions;

export type VehicleModel<M extends VehicleMake> =
  (typeof vehicleOptions)[M][number];

export const vehicleMakes = Object.keys(vehicleOptions).sort() as VehicleMake[];

export function getModelsForMake(make?: string | null): string[] {
  if (!make) return [];
  const key = make.trim().toLowerCase() as VehicleMake;
  return key in vehicleOptions ? [...vehicleOptions[key]] : [];
}