import { VehicleFailureMapEntry } from "./types";

export const vehicleFailureMap: VehicleFailureMapEntry[] = [
  {
    id: "ford_fiesta_1.0_ecoboost_2013_2019",
    make: "ford",
    model: "fiesta",
    engine: "1.0 ecoboost",
    engine_family: "ecoboost",
    engine_size: "1.0",
    fuel: "petrol",
    year_from: 2013,
    year_to: 2019,
    failure_codes: ["WET_BELT_ECOBOOST", "WATER_PUMP_LEAK"],
  },
  {
    id: "ford_fiesta_1.0_petrol_2013_2019_fallback",
    make: "ford",
    model: "fiesta",
    engine_size: "1.0",
    fuel: "petrol",
    year_from: 2013,
    year_to: 2019,
    failure_codes: ["WET_BELT_ECOBOOST", "WATER_PUMP_LEAK"],
  },
  {
    id: "ford_focus_1.0_ecoboost_2012_2019",
    make: "ford",
    model: "focus",
    engine: "1.0 ecoboost",
    engine_family: "ecoboost",
    engine_size: "1.0",
    fuel: "petrol",
    year_from: 2012,
    year_to: 2019,
    failure_codes: ["WET_BELT_ECOBOOST", "WATER_PUMP_LEAK"],
  },
  {
    id: "ford_focus_1.0_petrol_2012_2019_fallback",
    make: "ford",
    model: "focus",
    engine_size: "1.0",
    fuel: "petrol",
    year_from: 2012,
    year_to: 2019,
    failure_codes: ["WET_BELT_ECOBOOST", "WATER_PUMP_LEAK"],
  },
  {
    id: "ford_focus_1.6_tdci_2011_2018",
    make: "ford",
    model: "focus",
    engine: "1.6 tdci",
    engine_size: "1.6",
    fuel: "diesel",
    year_from: 2011,
    year_to: 2018,
    failure_codes: ["TURBO_FAILURE", "EGR_VALVE_CLOGGING", "DPF_BLOCKAGE"],
  },
  {
    id: "ford_focus_1.6_diesel_2011_2018_fallback",
    make: "ford",
    model: "focus",
    engine_size: "1.6",
    fuel: "diesel",
    year_from: 2011,
    year_to: 2018,
    failure_codes: ["TURBO_FAILURE", "EGR_VALVE_CLOGGING", "DPF_BLOCKAGE"],
  },
  {
    id: "bmw_1_series_116d_118d_n47_2008_2015",
    make: "bmw",
    model: "1 series",
    engine_family: "n47",
    fuel: "diesel",
    year_from: 2008,
    year_to: 2015,
    failure_codes: [
      "BMW_N47_TIMING_CHAIN",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "CLUTCH_DUAL_MASS_FLYWHEEL",
    ],
  },
  {
    id: "bmw_1_series_2.0_diesel_2008_2015_fallback",
    make: "bmw",
    model: "1 series",
    engine_size: "2.0",
    fuel: "diesel",
    year_from: 2008,
    year_to: 2015,
    failure_codes: [
      "BMW_N47_TIMING_CHAIN",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "CLUTCH_DUAL_MASS_FLYWHEEL",
    ],
  },
  {
    id: "bmw_3_series_316d_318d_320d_n47_2008_2015",
    make: "bmw",
    model: "3 series",
    engine_family: "n47",
    fuel: "diesel",
    year_from: 2008,
    year_to: 2015,
    failure_codes: [
      "BMW_N47_TIMING_CHAIN",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "CLUTCH_DUAL_MASS_FLYWHEEL",
    ],
  },
  {
    id: "bmw_3_series_2.0_diesel_2008_2015_fallback",
    make: "bmw",
    model: "3 series",
    engine_size: "2.0",
    fuel: "diesel",
    year_from: 2008,
    year_to: 2015,
    failure_codes: [
      "BMW_N47_TIMING_CHAIN",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "CLUTCH_DUAL_MASS_FLYWHEEL",
    ],
  },
  {
    id: "bmw_5_series_520d_n47_2010_2014",
    make: "bmw",
    model: "5 series",
    engine_family: "n47",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2014,
    failure_codes: [
      "BMW_N47_TIMING_CHAIN",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
    ],
  },
  {
    id: "bmw_5_series_2.0_diesel_2010_2014_fallback",
    make: "bmw",
    model: "5 series",
    engine_size: "2.0",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2014,
    failure_codes: [
      "BMW_N47_TIMING_CHAIN",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
    ],
  },
  {
    id: "vw_golf_2.0_tdi_dsg_2009_2019",
    make: "volkswagen",
    model: "golf",
    engine: "2.0 tdi",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2009,
    year_to: 2019,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "TURBO_FAILURE",
    ],
  },
  {
    id: "vw_golf_2.0_diesel_auto_2009_2019_fallback",
    make: "volkswagen",
    model: "golf",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2009,
    year_to: 2019,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "TURBO_FAILURE",
    ],
  },
  {
    id: "vw_golf_2.0_diesel_2009_2019_broad",
    make: "volkswagen",
    model: "golf",
    engine_size: "2.0",
    fuel: "diesel",
    year_from: 2009,
    year_to: 2019,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "vw_golf_1.6_tdi_dsg_2009_2019",
    make: "volkswagen",
    model: "golf",
    engine: "1.6 tdi",
    engine_size: "1.6",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2009,
    year_to: 2019,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
    ],
  },
  {
    id: "vw_golf_1.6_diesel_auto_2009_2019_fallback",
    make: "volkswagen",
    model: "golf",
    engine_size: "1.6",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2009,
    year_to: 2019,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
    ],
  },
  {
    id: "vw_golf_1.4_tsi_2008_2014",
    make: "volkswagen",
    model: "golf",
    engine: "1.4 tsi",
    engine_size: "1.4",
    fuel: "petrol",
    year_from: 2008,
    year_to: 2014,
    failure_codes: ["VW_TSI_TIMING_CHAIN", "TURBO_FAILURE"],
  },
  {
    id: "vw_golf_1.4_petrol_2008_2014_fallback",
    make: "volkswagen",
    model: "golf",
    engine_size: "1.4",
    fuel: "petrol",
    year_from: 2008,
    year_to: 2014,
    failure_codes: ["VW_TSI_TIMING_CHAIN", "TURBO_FAILURE"],
  },
  {
    id: "vw_passat_2.0_tdi_dsg_2010_2019",
    make: "volkswagen",
    model: "passat",
    engine: "2.0 tdi",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2010,
    year_to: 2019,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "TURBO_FAILURE",
    ],
  },
  {
    id: "vw_passat_2.0_diesel_auto_2010_2019_fallback",
    make: "volkswagen",
    model: "passat",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2010,
    year_to: 2019,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "TURBO_FAILURE",
    ],
  },
  {
    id: "audi_a3_2.0_tdi_s_tronic_2009_2019",
    make: "audi",
    model: "a3",
    engine: "2.0 tdi",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2009,
    year_to: 2019,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "TURBO_FAILURE",
    ],
  },
  {
    id: "audi_a3_2.0_diesel_auto_2009_2019_fallback",
    make: "audi",
    model: "a3",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2009,
    year_to: 2019,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "TURBO_FAILURE",
    ],
  },
  {
    id: "audi_a4_2.0_tdi_s_tronic_2009_2019",
    make: "audi",
    model: "a4",
    engine: "2.0 tdi",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2009,
    year_to: 2019,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "TURBO_FAILURE",
    ],
  },
  {
    id: "audi_a4_2.0_diesel_auto_2009_2019_fallback",
    make: "audi",
    model: "a4",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2009,
    year_to: 2019,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "TURBO_FAILURE",
    ],
  },
  {
    id: "skoda_octavia_2.0_tdi_dsg_2010_2020",
    make: "skoda",
    model: "octavia",
    engine: "2.0 tdi",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2010,
    year_to: 2020,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
    ],
  },
  {
    id: "skoda_octavia_2.0_diesel_auto_2010_2020_fallback",
    make: "skoda",
    model: "octavia",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2010,
    year_to: 2020,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
    ],
  },
  {
    id: "seat_leon_2.0_tdi_dsg_2010_2020",
    make: "seat",
    model: "leon",
    engine: "2.0 tdi",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2010,
    year_to: 2020,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
    ],
  },
  {
    id: "seat_leon_2.0_diesel_auto_2010_2020_fallback",
    make: "seat",
    model: "leon",
    engine_size: "2.0",
    fuel: "diesel",
    transmission: "automatic",
    year_from: 2010,
    year_to: 2020,
    failure_codes: [
      "VW_DSG_MECHATRONICS",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
    ],
  },
  {
    id: "vauxhall_astra_1.6_cdti_2014_2020",
    make: "vauxhall",
    model: "astra",
    engine: "1.6 cdti",
    engine_size: "1.6",
    fuel: "diesel",
    year_from: 2014,
    year_to: 2020,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "vauxhall_astra_1.6_diesel_2014_2020_fallback",
    make: "vauxhall",
    model: "astra",
    engine_size: "1.6",
    fuel: "diesel",
    year_from: 2014,
    year_to: 2020,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "vauxhall_insignia_2.0_cdti_2009_2017",
    make: "vauxhall",
    model: "insignia",
    engine: "2.0 cdti",
    engine_size: "2.0",
    fuel: "diesel",
    year_from: 2009,
    year_to: 2017,
    failure_codes: [
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "TURBO_FAILURE",
      "CLUTCH_DUAL_MASS_FLYWHEEL",
    ],
  },
  {
    id: "vauxhall_insignia_2.0_diesel_2009_2017_fallback",
    make: "vauxhall",
    model: "insignia",
    engine_size: "2.0",
    fuel: "diesel",
    year_from: 2009,
    year_to: 2017,
    failure_codes: [
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "TURBO_FAILURE",
      "CLUTCH_DUAL_MASS_FLYWHEEL",
    ],
  },
  {
    id: "peugeot_308_1.6_hdi_2010_2018",
    make: "peugeot",
    model: "308",
    engine: "1.6 hdi",
    engine_size: "1.6",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2018,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "peugeot_308_1.6_diesel_2010_2018_fallback",
    make: "peugeot",
    model: "308",
    engine_size: "1.6",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2018,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "citroen_c4_1.6_hdi_2010_2018",
    make: "citroen",
    model: "c4",
    engine: "1.6 hdi",
    engine_size: "1.6",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2018,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "citroen_c4_1.6_diesel_2010_2018_fallback",
    make: "citroen",
    model: "c4",
    engine_size: "1.6",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2018,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "mazda_3_2.2_diesel_2014_2019",
    make: "mazda",
    model: "3",
    engine: "2.2 diesel",
    engine_size: "2.2",
    fuel: "diesel",
    year_from: 2014,
    year_to: 2019,
    failure_codes: ["DPF_BLOCKAGE", "TURBO_FAILURE", "WATER_PUMP_LEAK"],
  },
  {
    id: "nissan_qashqai_1.5_dci_2010_2020",
    make: "nissan",
    model: "qashqai",
    engine: "1.5 dci",
    engine_size: "1.5",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2020,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "nissan_qashqai_1.5_diesel_2010_2020_fallback",
    make: "nissan",
    model: "qashqai",
    engine_size: "1.5",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2020,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "renault_clio_1.5_dci_2012_2020",
    make: "renault",
    model: "clio",
    engine: "1.5 dci",
    engine_size: "1.5",
    fuel: "diesel",
    year_from: 2012,
    year_to: 2020,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "renault_clio_1.5_diesel_2012_2020_fallback",
    make: "renault",
    model: "clio",
    engine_size: "1.5",
    fuel: "diesel",
    year_from: 2012,
    year_to: 2020,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "renault_megane_1.5_dci_2010_2020",
    make: "renault",
    model: "megane",
    engine: "1.5 dci",
    engine_size: "1.5",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2020,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "renault_megane_1.5_diesel_2010_2020_fallback",
    make: "renault",
    model: "megane",
    engine_size: "1.5",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2020,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "mini_cooper_d_1.6_2007_2014",
    make: "mini",
    model: "cooper",
    engine: "1.6 diesel",
    engine_size: "1.6",
    fuel: "diesel",
    year_from: 2007,
    year_to: 2014,
    failure_codes: ["TURBO_FAILURE", "EGR_VALVE_CLOGGING", "DPF_BLOCKAGE"],
  },
  {
    id: "mini_cooper_s_1.6_2007_2014",
    make: "mini",
    model: "cooper",
    engine: "1.6 turbo",
    engine_size: "1.6",
    fuel: "petrol",
    year_from: 2007,
    year_to: 2014,
    failure_codes: ["TURBO_FAILURE", "WATER_PUMP_LEAK"],
  },
  {
    id: "land_rover_freelander_2_2_td4_2007_2014",
    make: "land rover",
    model: "freelander",
    engine: "2.2 td4",
    engine_size: "2.2",
    fuel: "diesel",
    year_from: 2007,
    year_to: 2014,
    failure_codes: [
      "TURBO_FAILURE",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "SUSPENSION_BUSH_WEAR",
    ],
  },
  {
    id: "range_rover_evoque_2.2_diesel_2011_2018",
    make: "range rover",
    model: "evoque",
    engine: "2.2 diesel",
    engine_size: "2.2",
    fuel: "diesel",
    year_from: 2011,
    year_to: 2018,
    failure_codes: [
      "TURBO_FAILURE",
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "SUSPENSION_BUSH_WEAR",
    ],
  },
  {
    id: "mercedes_c_class_220_cdi_2008_2015",
    make: "mercedes",
    model: "c class",
    engine: "220 cdi",
    fuel: "diesel",
    year_from: 2008,
    year_to: 2015,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "mercedes_e_class_220_cdi_2009_2016",
    make: "mercedes",
    model: "e class",
    engine: "220 cdi",
    fuel: "diesel",
    year_from: 2009,
    year_to: 2016,
    failure_codes: [
      "EGR_VALVE_CLOGGING",
      "DPF_BLOCKAGE",
      "TURBO_FAILURE",
      "CLUTCH_DUAL_MASS_FLYWHEEL",
    ],
  },
  {
    id: "hyundai_ix35_1.7_crdi_2010_2015",
    make: "hyundai",
    model: "ix35",
    engine: "1.7 crdi",
    engine_size: "1.7",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2015,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "kia_sportage_1.7_crdi_2011_2018",
    make: "kia",
    model: "sportage",
    engine: "1.7 crdi",
    engine_size: "1.7",
    fuel: "diesel",
    year_from: 2011,
    year_to: 2018,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
  {
    id: "toyota_avensis_2.0_d4d_2009_2018",
    make: "toyota",
    model: "avensis",
    engine: "2.0 d-4d",
    engine_size: "2.0",
    fuel: "diesel",
    year_from: 2009,
    year_to: 2018,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "WATER_PUMP_LEAK"],
  },
  {
    id: "honda_civic_2.2_ctdi_2006_2011",
    make: "honda",
    model: "civic",
    engine: "2.2 ctdi",
    engine_size: "2.2",
    fuel: "diesel",
    year_from: 2006,
    year_to: 2011,
    failure_codes: ["TURBO_FAILURE", "CLUTCH_DUAL_MASS_FLYWHEEL"],
  },
  {
    id: "honda_crv_2.2_idtec_2010_2017",
    make: "honda",
    model: "cr-v",
    engine: "2.2 i-dtec",
    engine_size: "2.2",
    fuel: "diesel",
    year_from: 2010,
    year_to: 2017,
    failure_codes: ["EGR_VALVE_CLOGGING", "DPF_BLOCKAGE", "TURBO_FAILURE"],
  },
];